name: Daily GitHub Trending Fetch

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 UTC 자정에 실행 (한국 시간으로는 오전 9시)
  workflow_dispatch:      # 수동 트리거 옵션 추가

# 저장소에 쓰기 권한 부여
permissions:
  contents: write

jobs:
  fetch-trending:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 openai python-dotenv postgrest supabase
          
      - name: Create data directory
        run: mkdir -p data
          
      - name: Fetch GitHub trending
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SECRET: ${{ secrets.SUPABASE_SECRET }}
        run: python fetch_github_trending.py
        
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/
          git commit -m "Update GitHub trending data for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
